### ISSUE TITLE
Definition for findByApplicationIdInAndCreatedBetweenOrderByCreated

### ISSUE THREAD

**Issue by venkiit58** [awconstable/deployservice#45]
Thank you for this project, this actually helps for a quick start with collecting metrics. I'm curious where can I find logic for findByApplicationIdInAndCreatedBetweenOrderByCreated, I didn't find in the repo. I suppose you are referring it from org.springframework.stereotype.Repository or org.springframework.data.mongodb.repository.MongoRepository? I'd like to know how this is being calculated. Please share if possible.

**Comment by awconstable** [comment]
Hi @venkiit58 - this method is using Spring Data JPA, so there's no calculation behind it, the method just brings back raw data. If you're interested in understanding how the Lead Time and Deployment Frequency is calculated then check out: https://github.com/awconstable/deployservice/blob/main/src/main/java/team/deployservice/service/DeploymentServiceImpl.java

**Comment by venkiit58** [comment]
Thanks @awconstable . Yes I checked it already, however I am curious to know the query behind it because I'm trying to building something similar in our project but need to understand the formulae. Appreciate if you can help me with the formulae.
